### ISSUE TITLE
TUTO

### ISSUE THREAD

**Issue by 0xChqrles** [0xChqrles/ESILV-basecamp#1]

**Comment by 0xChqrles** [comment]
SCARB: `curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh`

SNCAST: `curl -L https://raw.githubusercontent.com/foundry-rs/starknet-foundry/master/scripts/install.sh | sh`
`foundryup`
`curl -L https://raw.githubusercontent.com/software-mansion/universal-sierra-compiler/master/scripts/install.sh | sh`

**Comment by 0xChqrles** [comment]
FOUNDRY DOC (for sncast): https://foundry-rs.github.io/starknet-foundry/

SCARB DOC: https://docs.swmansion.com/scarb/

**Comment by 0xChqrles** [comment]
RUST: `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

**Comment by 0xChqrles** [comment]
OZ: `scarb add openzeppelin@0.20.0`

**Comment by 0xChqrles** [comment]
https://github.com/OpenZeppelin/cairo-contracts/blob/main/packages/presets/src/erc20.cairo

**Comment by 0xChqrles** [comment]
RPC: https://voyager.online/

**Comment by 0xChqrles** [comment]
FAUCET: https://starknet-faucet.vercel.app/

**Comment by 0xChqrles** [comment]
create account:

`sncast account create --name <NAME> --url <RPC_URL>`

deploy account:

`sncast account deploy --name <NAME> --url <RPC_URL>`

**Comment by 0xChqrles** [comment]
declare:

`sncast --account <ACCOUNT_NAME> declare --contract-name <CONTRACT_NAME> --url  <RPC_URL>`

**Comment by 0xChqrles** [comment]
```toml
[package]
name = "esilv"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
openzeppelin = "0.20.0"
starknet = "2.9.2"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.30.0" }

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
```
